name: build

on:
  push:
    branches:
      - develop
      - master
      - releases/*
  pull_request:
  schedule:
    - cron: '30 6 * * 1'

jobs:
  build:
    name: Build
    runs-on: macos-12
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
            submodules: 'recursive'
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Build the app
        run: ./scripts/test-build.sh script -v2